// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $asmr from "./routes/asmr.tsx";
import * as $hics_1 from "./routes/hics/1.tsx";
import * as $hics_2 from "./routes/hics/2.tsx";
import * as $hics_index from "./routes/hics/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $mega_1 from "./routes/mega/1.tsx";
import * as $mega_2 from "./routes/mega/2.tsx";
import * as $mega_index from "./routes/mega/index.tsx";
import * as $plush from "./routes/plush.tsx";
import * as $vods from "./routes/vods.tsx";
import * as $database from "./islands/database.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/asmr.tsx": $asmr,
    "./routes/hics/1.tsx": $hics_1,
    "./routes/hics/2.tsx": $hics_2,
    "./routes/hics/index.tsx": $hics_index,
    "./routes/index.tsx": $index,
    "./routes/mega/1.tsx": $mega_1,
    "./routes/mega/2.tsx": $mega_2,
    "./routes/mega/index.tsx": $mega_index,
    "./routes/plush.tsx": $plush,
    "./routes/vods.tsx": $vods,
  },
  islands: {
    "./islands/database.tsx": $database,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
